### ISSUE TITLE
Parse cookies to session not working

### ISSUE THREAD

**Issue by AndresQuiVal** [rastvl/cloudflare-cookies-generator#2]
Hello again @rastvl , i have succesfully obtained the cookies from my test site with cloudflare but when moving those cookies to an python session and then make a request to some endpoint of the website seems not to work, gives `403`, are there some session parameters i need to consider to parse the session correctly from the library to my code pr what else i need to consider? Thanks

**Comment by rastvl** [comment]
@AndresQuiVal This repository is only related to getting cookies. If cookies are received, that's all the headless browser required. It's up to you to figure out how to handle them properly. 
PS. Your problem is most likely related to the TLS Fingerprint. Also remember that userAgent and proxy must match
